# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FeZGQjGMWkN_Y32uWzvRyTRvRFM6kvd
"""

import streamlit as st
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Load the dataset from a relative path
data_path = os.path.join(os.path.dirname(__file__), 'labeled_clusters_dataset.csv')
df = pd.read_csv(data_path)

# Define the recommendation function
def recommend_song(selected_song, df):
    song_index = df[df['Track Name'] == selected_song].index[0]
    song_features = df.drop(['Track Name', 'Cluster', 'Cluster Label', 'PCA1', 'PCA2'], axis=1).iloc[song_index]
    similarities = cosine_similarity([song_features], df.drop(['Track Name', 'Cluster', 'Cluster Label'], axis=1))
    similar_indices = similarities[0].argsort()[-6:-1][::-1]
    recommended_songs = df.iloc[similar_indices][['Track Name', 'Danceability', 'Tempo', 'Valence']]
    return recommended_songs

# Streamlit UI
st.title("Spotify Song Recommendation")

# Dropdown to select a song
selected_song = st.selectbox("Choose a Song", df['Track Name'].unique())

# Button to get recommendations
if st.button("Get Recommendations"):
    recommended_songs = recommend_song(selected_song, df)

    st.write(f"Recommendations based on your choice of: **{selected_song}**")
    st.write(recommended_songs)